# Generated by Django 5.2.3 on 2025-06-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('channel_id', models.CharField(max_length=100)),
                ('message_type', models.CharField(choices=[('natural_language', 'Natural Language'), ('slash_command', 'Slash Command'), ('followup', 'Follow-up Question'), ('general_chat', 'General Chat')], max_length=50)),
                ('user_message', models.TextField()),
                ('bot_response', models.TextField()),
                ('intent_classified', models.CharField(blank=True, max_length=100)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('channel_id', models.CharField(max_length=100)),
                ('last_read_ts', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user_id', 'channel_id')},
            },
        ),
    ]
