# Generated by Django 5.2.3 on 2025-06-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_chatbotinteraction_userreadstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelsummary',
            name='timeframe_hours',
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name='conversationcontext',
            name='last_interaction_type',
            field=models.CharField(default='summary', max_length=50),
        ),
        migrations.AddField(
            model_name='chatbotinteraction',
            name='extracted_parameters',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='chatbotinteraction',
            name='message_type',
            field=models.CharField(choices=[('natural_language', 'Natural Language'), ('slash_command', 'Slash Command'), ('followup', 'Follow-up Question'), ('general_chat', 'General Chat'), ('intent_summary', 'Intent: Summary Request'), ('intent_help', 'Intent: Help Request'), ('intent_status', 'Intent: Status Check')], max_length=50),
        ),
        migrations.AlterField(
            model_name='conversationcontext',
            name='context_type',
            field=models.CharField(max_length=50),
        ),
    ]
