# Generated by Django 5.2.3 on 2025-06-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_chatbot_enhancements'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelsummary',
            name='summary_type',
            field=models.CharField(choices=[('regular', 'Regular Time-based Summary'), ('unread', 'Unread Messages Summary')], default='regular', max_length=50),
        ),
    ]
