# Generated by Django 5.2.3 on 2025-07-01 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_channelcategory_categorysummary_categorychannel'),
    ]

    operations = [
        # Add indexes to ChannelCategory
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS bot_channelcategory_workspace_name_idx ON bot_channelcategory (workspace_id, name);",
            reverse_sql="DROP INDEX IF EXISTS bot_channelcategory_workspace_name_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS bot_channelcategory_created_by_user_idx ON bot_channelcategory (created_by_user);",
            reverse_sql="DROP INDEX IF EXISTS bot_channelcategory_created_by_user_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS bot_channelcategory_created_at_idx ON bot_channelcategory (created_at);",
            reverse_sql="DROP INDEX IF EXISTS bot_channelcategory_created_at_idx;"
        ),
        
        # Add indexes to CategoryChannel
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS bot_categorychannel_category_idx ON bot_categorychannel (category_id);",
            reverse_sql="DROP INDEX IF EXISTS bot_categorychannel_category_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS bot_categorychannel_channel_idx ON bot_categorychannel (channel_id);",
            reverse_sql="DROP INDEX IF EXISTS bot_categorychannel_channel_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS bot_categorychannel_added_by_user_idx ON bot_categorychannel (added_by_user);",
            reverse_sql="DROP INDEX IF EXISTS bot_categorychannel_added_by_user_idx;"
        ),
        
        # Add indexes to CategorySummary
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS bot_categorysummary_category_idx ON bot_categorysummary (category_id);",
            reverse_sql="DROP INDEX IF EXISTS bot_categorysummary_category_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS bot_categorysummary_requested_by_user_idx ON bot_categorysummary (requested_by_user);",
            reverse_sql="DROP INDEX IF EXISTS bot_categorysummary_requested_by_user_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS bot_categorysummary_created_at_idx ON bot_categorysummary (created_at);",
            reverse_sql="DROP INDEX IF EXISTS bot_categorysummary_created_at_idx;"
        ),
        
        # Update model meta options
        migrations.AlterModelOptions(
            name='channelcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Channel Categories'},
        ),
        migrations.AlterModelOptions(
            name='categorysummary',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Category Summaries'},
        ),
    ]
