# Generated by Django 5.2.3 on 2025-07-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_add_categorysummary_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='categorychannel',
            index=models.Index(fields=['category'], name='bot_categor_categor_fdb6ff_idx'),
        ),
        migrations.AddIndex(
            model_name='categorychannel',
            index=models.Index(fields=['channel'], name='bot_categor_channel_956776_idx'),
        ),
        migrations.AddIndex(
            model_name='categorychannel',
            index=models.Index(fields=['added_by_user'], name='bot_categor_added_b_34b24c_idx'),
        ),
        migrations.AddIndex(
            model_name='categorysummary',
            index=models.Index(fields=['category'], name='bot_categor_categor_249448_idx'),
        ),
        migrations.AddIndex(
            model_name='categorysummary',
            index=models.Index(fields=['requested_by_user'], name='bot_categor_request_60a9e1_idx'),
        ),
        migrations.AddIndex(
            model_name='categorysummary',
            index=models.Index(fields=['created_at'], name='bot_categor_created_e87e89_idx'),
        ),
        migrations.AddIndex(
            model_name='channelcategory',
            index=models.Index(fields=['workspace', 'name'], name='bot_channel_workspa_103091_idx'),
        ),
        migrations.AddIndex(
            model_name='channelcategory',
            index=models.Index(fields=['created_by_user'], name='bot_channel_created_17fad4_idx'),
        ),
        migrations.AddIndex(
            model_name='channelcategory',
            index=models.Index(fields=['created_at'], name='bot_channel_created_13c962_idx'),
        ),
    ]
