# Generated by Django 5.2.3 on 2025-07-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_add_task_todo_management'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channeltodo',
            name='canvas_block_id',
        ),
        migrations.RemoveField(
            model_name='channelcanvas',
            name='channel',
        ),
        migrations.DeleteModel(
            name='ChannelCanvas',
        ),
        migrations.AlterModelOptions(
            name='channeltodo',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='channeltodo',
            name='bot_channel_channel_22228f_idx',
        ),
        migrations.RemoveIndex(
            model_name='channeltodo',
            name='bot_channel_assigne_3e9145_idx',
        ),
        migrations.RemoveIndex(
            model_name='channeltodo',
            name='bot_channel_task_ty_2d68d0_idx',
        ),
        migrations.AddIndex(
            model_name='channeltodo',
            index=models.Index(fields=['created_by'], name='bot_channel_created_3c2abd_idx'),
        ),
        migrations.AddIndex(
            model_name='channeltodo',
            index=models.Index(fields=['assigned_to'], name='bot_channel_assigne_ea09e5_idx'),
        ),
    ]
